task:
  matrix:
    - name: Meson / freebsd/gcc-12
      freebsd_instance:
        image: freebsd-13-3-release-amd64
    - name: Meson / macos-silicon/gcc-14
      macos_instance:
        image: ghcr.io/cirruslabs/macos-ventura-base:latest
  dependencies_script: |
    echo $(uname)
    if [ "$(uname)" = "FreeBSD" ]; then
      pkg install -y py39-pip meson bash gcc12
    else
      brew install python meson gcc@14
    fi
  configure_script: |
    if [ "$(uname -s)" = "FreeBSD" ]; then
      FC=gfortran12 CC=gcc12 CXX=g++12 meson setup builddir --prefix=${CIRRUS_WORKING_DIR}/../meson
    else
      FC=gfortran-14 CC=gcc-14 CXX=g++-14 meson setup builddir --prefix=${CIRRUS_WORKING_DIR}/../meson
    fi
  build_script: |
    meson compile -C builddir
  install_script: |
    meson install -C builddir
  test_script: |
    meson test -C builddir
  on_failure:
    log_artifacts:
      path: builddir/meson-logs/*log.txt
