language: bash

os:
  - linux
  - osx

sudo: required

branches:
  only:
    - master

notifications:
  email: false

env:
  - SIFDECODE_VERSION=2.0.0
  - SIFDECODE_VERSION=master

before_install:
  - export ARCHDEFS_VERSION=2.0.2
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then sudo apt-get update -qq; sudo apt-get install -qq wget gfortran libblas-dev liblapack-dev; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew update; brew cask uninstall oclint; brew install gcc; fi
  - mkdir -p $HOME/archdefs
  - cd $HOME/archdefs
  - wget https://github.com/ralna/ARCHDefs/archive/v$ARCHDEFS_VERSION.tar.gz
  - export ARCHDEFS=$HOME/archdefs/ARCHDefs-$ARCHDEFS_VERSION
  - tar xvf v$ARCHDEFS_VERSION.tar.gz
  - mkdir -p $HOME/sifdecode
  - cd $HOME/sifdecode
  - if [[ $SIFDECODE_VERSION == "master" ]]; then
      git clone https://github.com/ralna/SIFDecode.git;
      export SIFDECODE=$HOME/sifdecode/SIFDecode;
    else
      wget https://github.com/ralna/SIFDecode/archive/v$SIFDECODE_VERSION.tar.gz;
      export SIFDECODE=$HOME/sifdecode/SIFDecode-$SIFDECODE_VERSION;
      tar xvf v$SIFDECODE_VERSION.tar.gz;
    fi
  - cd $SIFDECODE
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then printf "6\n2\n4\n" > sifdecode.input; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then printf "13\n2\n" > sifdecode.input; fi
  - printf "nny" >> sifdecode.input
  - ./install_sifdecode < sifdecode.input
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export MYARCH=pc64.lnx.gfo; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then export MYARCH=mac64.osx.gfo; fi
  - export CUTEST=$TRAVIS_BUILD_DIR
  - export MASTSIF=$SIFDECODE/sif
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi

install:
  - cd $TRAVIS_BUILD_DIR
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then printf "6\n2\n4\n2\n7\n" > cutest.input; fi
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then printf "13\n2\n2\n5\n" > cutest.input; fi
  - printf "nnydy" >> cutest.input
  - ./install_cutest < cutest.input

script:
  - ./bin/runcutest -p gen77 -param NN=10 -D LUBRIFC.SIF
  - ./bin/runcutest -p genc
  - ./bin/runcutest -p gen90
  - ./bin/runcutest -p stats
  - ./bin/runcutest --single -p gen77
  - ./bin/runcutest --single -p genc
  - ./bin/runcutest --single -p gen90
  - ./bin/runcutest --single -p stats
  - ./bin/runcutest -p gen77 -b -lblas -K -llapack -D ROSENBR
  - ./bin/runcutest -p gen77 -lblas -D ROSENBR

