      1000    ILIM,    the maximum number of iterations
   0.00001    GRADTL,  the relative gradient stopping tolerance
         2    IAGFLG,  the gradient availability and checking flag
         2    IAHFLG,  the Hessian availability and checking flag
       1.0    FSCALE,  the typical value of the objective function
       1.0    TYPX,    the typical value of the problem's variables
         1    METHOD,  the method used (0 = Newton, 1 = tensor )
        15    NDIGIT,  the number of accurate digits in function values
         1    MSG,     the output specifier
