'\" e  @(#)cutest_uvarty v1.0 12/2012;
.TH cutest_uvartype 3M "4 Dec 2012" "CUTEst user documentation" "CUTEst user documentation"
.SH NAME
CUTEST_uvartype \- CUTEst tool to determine the type of each variable.
.SH SYNOPSIS
.HP 1i
CALL CUTEST_uvartype( status, n, X_type )

.HP 1i
For real rather than double precision arguments, instead

.HP 1i
CALL CUTEST_uvartype_s( ... )

.HP 1i
and for quadruple precision arguments, when available,

.HP 1i
CALL CUTEST_uvartype_q( ... )

.SH DESCRIPTION
The CUTEST_uvartype subroutine determines the type (continuous, 0-1,
integer) of each variable involved in the problem decoded
from a SIF file by the script \fIsifdecoder\fP.

The problem under consideration
is to minimize or maximize an objective function
.EQ
f(x)
.EN
over all
.EQ
x
.EN
\(mo
.EQ
R sup n
.EN
subject to the simple bounds
.EQ
x sup l ~<=~ x ~<=~ x sup u.
.EN
The objective function is group-partially separable.

.LP 
.SH ARGUMENTS
The arguments of CUTEST_uvartype are as follows
.TP 5
.B status \fP[out] - integer
the outputr status: 0 for a succesful call, 1 for an array 
allocation/deallocation error, 2 for an array bound error,
3 for an evaluation error,
.TP
.B n \fP[in] - integer
the number of variables for the problem,
.TP
.B X_type \fP[out] - integer
an integer array whose i-th component indicates the type of variable
i. Possible values are 0 (a variable whose value may be any real
number), 1 (an integer variable that can only take the values zero or
one) and 2 (a variable that can only take integer values). 
.LP
.SH AUTHORS
I. Bongartz, A.R. Conn, N.I.M. Gould, D. Orban and Ph.L. Toint
.SH "SEE ALSO"
\fICUTEst: a Constrained and Unconstrained Testing 
Environment with safe threads\fP,
   N.I.M. Gould, D. Orban and Ph.L. Toint,
   Computational Optimization and Applications \fB60\fP:3, pp.545-557, 2014.

\fICUTEr (and SifDec): A Constrained and Unconstrained Testing
Environment, revisited\fP,
   N.I.M. Gould, D. Orban and Ph.L. Toint,
   ACM TOMS, \fB29\fP:4, pp.373-394, 2003.

\fICUTE: Constrained and Unconstrained Testing Environment\fP,
   I. Bongartz, A.R. Conn, N.I.M. Gould and Ph.L. Toint, 
   ACM TOMS, \fB21\fP:1, pp.123-160, 1995.

cutest_cvartype(3M), sifdecoder(1).
