'\" e  @(#)cutest_csjp v1.6 03/2018;
.TH cutest_csjp 3M "22 Feb 2018" "CUTEst user documentation" "CUTEst user documentation"
.SH NAME
CUTEST_csjp \- CUTEst tool to evaluate the sparsity pattern of the
Jacobian of constraints gradients.
.SH SYNOPSIS
.HP 1i
CALL CUTEST_csjp( status, nnzj, lj, J_var, J_con )

.HP 1i
For real rather than double precision arguments, instead

.HP 1i
CALL CUTEST_csjp_s( ... )

.HP 1i
and for quadruple precision arguments, when available,

.HP 1i
CALL CUTEST_csjp_q( ... )

.SH DESCRIPTION
The CUTEST_csjp subroutine evaluates the sparsity pattern used when storing the
Jacobian matrix of gradients of the general constraints
corresponding to the problem decoded from a SIF file by the script
\fIsifdecoder\fP.

The problem under consideration
is to minimize or maximize an objective function
.EQ
f(x)
.EN
over all
.EQ
x
.EN
\(mo
.EQ
R sup n
.EN
subject to
general equations
.EQ
c sub i (x) ~=~ 0,
.EN
.EQ
~(i
.EN
\(mo
.EQ
{ 1 ,..., m sub E } ),
.EN
general inequalities
.EQ
c sub i sup l ~<=~ c sub i (x) ~<=~ c sub i sup u,
.EN
.EQ
~(i
.EN
\(mo
.EQ
{ m sub E + 1 ,..., m }),
.EN
and simple bounds
.EQ
x sup l ~<=~ x ~<=~ x sup u.
.EN
The objective function is group-partially separable and
all constraint functions are partially separable.
.LP
.SH ARGUMENTS
The arguments of CUTEST_csjp are as follows
.TP 5
.B status \fP[out] - integer
the outputr status: 0 for a succesful call, 1 for an array
allocation/deallocation error, 2 for an array bound error,
3 for an evaluation error,
.TP
.B nnzj \fP[out] - integer
the number of nonzeros in J_var and J_con,
.TP
.B lj \fP[in] - integer
the actual declared dimensions of J_var and J_con,
.TP
.B J_var \fP[out] - integer
an array whose i-th component is the index of the variable with
respect to which the derivative is taken,
.TP
.B J_con \fP[out] - integer
an array whose i-th component is the index of the constraint function
whose derivative is taken.
.LP
.SH AUTHORS
I. Bongartz, A.R. Conn, N.I.M. Gould, D. Orban and Ph.L. Toint
.SH "SEE ALSO"
\fICUTEst: a Constrained and Unconstrained Testing
Environment with safe threads\fP,
   N.I.M. Gould, D. Orban and Ph.L. Toint,
   Computational Optimization and Applications \fB60\fP:3, pp.545-557, 2014.

\fICUTEr (and SifDec): A Constrained and Unconstrained Testing
Environment, revisited\fP,
   N.I.M. Gould, D. Orban and Ph.L. Toint,
   ACM TOMS, \fB29\fP:4, pp.373-394, 2003.

\fICUTE: Constrained and Unconstrained Testing Environment\fP,
   I. Bongartz, A.R. Conn, N.I.M. Gould and Ph.L. Toint,
   ACM TOMS, \fB21\fP:1, pp.123-160, 1995.

cutest_csgr(3M), sifdecoder(1).
