'\" e  @(#)cutest_timings v1.0 03/2016;
.TH cutest_timings 3 "3 Mar 2016" "CUTEst user documentation" "CUTEst user documentation"
.SH NAME
CUTEST_timings \- CUTEst tool to find the CPU time used by a CUTEst evaluation
subrotine.
.SH SYNOPSIS
.HP 1i
CALL CUTEST_timings( status, name, time )

.HP 1i
For real rather than double precision arguments, instead

.HP 1i
CALL CUTEST_timings_s( ... )

.HP 1i
and for quadruple precision arguments, when available,

.HP 1i
CALL CUTEST_timings_q( ... )

.SH DESCRIPTION
The CUTEST_timings subroutine obtains the CPU time used by an individual
CUTEst evaluation subroutine.

.LP
.SH ARGUMENTS
The arguments of CUTEST_timings are as follows
.TP 5
.B status \fP[out] - integer
the outputr status: 0 for a succesful call, 26 for a call to an unknown
evaluation routine,

.TP 5
.B name \fP[in] - character variable of variable length that either contains
the name of a CUTEst subroutine, or one of the words 'start' or 'stop'.
Supported values are:

.TP 6
 'start' starts to record timings for the CUTEst evaluation tools -
    recordings are initially turned off
.TP
 'stop' pauses the recording until another 'start' occurs
.TP
 name is the name of a CUTEst evaluation tool,
 where name is one of strings
 'cutest_ccf', 'cutest_ccfg', 'cutest_ccfsg', 'cutest_cch',
 'cutest_cchprods', 'cutest_ccifg', 'cutest_ccifsg',
 'cutest_cdh', 'cutest_cdhc', 'cutest_cdimchp',
 'cutest_ceh', 'cutest_cfn', 'cutest_cgr',
 'cutest_cgrdh', 'cutest_chcprod', 'cutest_chprod',
 'cutest_cifn', 'cutest_cigr', 'cutest_cisgr',
 'cutest_cidh', 'cutest_cish', 'cutest_cjprod',
 'cutest_clfg', 'cutest_cofg', 'cutest_cofsg',
 'cutest_csgr', 'cutest_csgreh', 'cutest_csgrsh',
 'cutest_csh', 'cutest_cshc', 'cutest_cshcprod',
 'cutest_cshp', 'cutest_cshprod', 'cutest_csjprod',
 'cutest_ubandh', 'cutest_udh', 'cutest_ueh',
 'cutest_ufn', 'cutest_ugr', 'cutest_ugrdh',
 'cutest_ugreh', 'cutest_ugrsh', 'cutest_uhprod',
 'cutest_uofg', 'cutest_ush', 'cutest_ushp' or
 'cutest_ushprod',
.TP 5
.B time \fP[out] - real that gives the recorded time for the named tool
 (or 0.0 if name is 'start', 'stop' or an unrecognised tool).
.LP
.SH AUTHORS
I. Bongartz, A.R. Conn, N.I.M. Gould, D. Orban and Ph.L. Toint
.SH "SEE ALSO"
\fICUTEst: a Constrained and Unconstrained Testing
Environment with safe threads\fP,
   N.I.M. Gould, D. Orban and Ph.L. Toint,
   Computational Optimization and Applications \fB60\fP:3, pp.545-557, 2014.

\fICUTEr (and SifDec): A Constrained and Unconstrained Testing
Environment, revisited\fP,
   N.I.M. Gould, D. Orban and Ph.L. Toint,
   ACM TOMS, \fB29\fP:4, pp.373-394, 2003.

\fICUTE: Constrained and Unconstrained Testing Environment\fP,
   I. Bongartz, A.R. Conn, N.I.M. Gould and Ph.L. Toint,
   ACM TOMS, \fB21\fP:1, pp.123-160, 1995.

sifdecode(1),
cutest(3M),
cutest_ccfg(3M),
cutest_ccfsg(3M),
cutest_cch(3M),
cutest_cchprods(3M),
cutest_ccifg(3M),
cutest_ccifsg(3M),
cutest_cdh(3M),
cutest_cdhc(3M),
cutest_cdimchp(3M),
cutest_ceh(3M),
cutest_cfn(3M),
cutest_cgr(3M),
cutest_cgrdh(3M),
cutest_chcprod(3M),
cutest_chprod(3M),
cutest_cifn(3M),
cutest_cigr(3M),
cutest_cisgr(3M),
cutest_cidh(3M),
cutest_cish(3M),
cutest_cjprod(3M),
cutest_clfg(3M),
cutest_cofg(3M),
cutest_cofsg(3M),
cutest_csgr(3M),
cutest_csgreh(3M),
cutest_csgrsh(3M),
cutest_csh(3M),
cutest_cshc(3M),
cutest_cshcprod(3M),
cutest_cshp(3M),
cutest_cshprod(3M),
cutest_csjprod(3M),
cutest_ubandh(3M),
cutest_udh(3M),
cutest_ueh(3M),
cutest_ufn(3M),
cutest_ugr(3M),
cutest_ugrdh(3M),
cutest_ugreh(3M),
cutest_ugrsh(3M),
cutest_uhprod(3M),
cutest_uofg(3M),
cutest_ush(3M),
cutest_ushp(3M),
cutest_ushprod(3M)
