#!/bin/csh

#foreach pack ( cutest_ccf \
#               cutest_ccfg \
#               cutest_ccfsg \
#               cutest_cchprods \
#               cutest_cchprodsp \
#               cutest_ccifg \
#               cutest_ccifsg \
#               cutest_cdh \
#               cutest_cdhc \
#               cutest_cdhj \
#               cutest_cdimchp \
#               cutest_cdimen \
#               cutest_cdimohp \
#               cutest_cdimse \
#               cutest_cdimsg \
#               cutest_cdimsh \
#               cutest_cdimsj \
#               cutest_ceh \
#               cutest_cfn \
#               cutest_cgr \
#               cutest_cgrdh \
#               cutest_chcprod \
#               cutest_chjprod \
#               cutest_chprod \
#               cutest_cidh \
#               cutest_cifn \
#               cutest_cigr \
#               cutest_cisgr \
#               cutest_cisgrp \
#               cutest_cish \
#               cutest_cjprod \
#               cutest_clfg \
#               cutest_cnames \
#               cutest_cofg \
#               cutest_cofsg \
#               cutest_cohprods \
#               cutest_cohprodsp \
#               cutest_connames \
#               cutest_creport \
#               cutest_csetup \
#               cutest_csgr \
#               cutest_csgreh \
#               cutest_csgrp \
#               cutest_csgrsh \
#               cutest_csgrshp \
#               cutest_csh \
#               cutest_cshc \
#               cutest_cshcprod \
#               cutest_cshj \
#               cutest_cshp \
#               cutest_cshprod \
#               cutest_csjp \
#               cutest_csjprod \
#               cutest_cterminate \
#               cutest_cvartype \
#               cutest_classification \
#               cutest_pname \
#               cutest_probname \
#               cutest_timings \
#               cutest_ubandh \
#               cutest_udh \
#               cutest_udimen \
#               cutest_udimse \
#               cutest_udimsh \
#               cutest_ueh \
#               cutest_ufn \
#               cutest_ugr \
#               cutest_ugrdh \
#               cutest_ugreh \
#               cutest_ugrsh \
#               cutest_uhprod \
#               cutest_unames \
#               cutest_uofg \
#               cutest_ureport \
#               cutest_usetup \
#               cutest_ush \
#               cutest_ushp \
#               cutest_ushprod \
#               cutest_uterminate \
#               cutest_uvartype \
#               cutest_varnames \
#               cutest_ccf_threaded \
#               cutest_ccfg_threaded \
#               cutest_ccfsg_threaded \
#               cutest_cchprods_threaded \
#               cutest_ccifg_threaded \
#               cutest_ccifsg_threaded \
#               cutest_cdh_threaded \
#               cutest_cdhc_threaded \
#               cutest_cdhj_threaded \
#               cutest_ceh_threaded \
#               cutest_cfn_threaded \
#               cutest_cgrdh_threaded \
#               cutest_cgr_threaded \
#               cutest_chcprod_threaded \
#               cutest_chjprod_threaded \
#               cutest_chprod_threaded \
#               cutest_cidh_threaded \
#               cutest_cifn_threaded \
#               cutest_cigr_threaded \
#               cutest_cisgr_threaded \
#               cutest_cish_threaded \
#               cutest_cjprod_threaded \
#               cutest_clfg_threaded \
#               cutest_cofg_threaded \
#               cutest_cofsg_threaded \
#               cutest_cohprods_threaded \
#               cutest_creport_threaded \
#               cutest_csetup_threaded \
#               cutest_csgreh_threaded \
#               cutest_csgrsh_threaded \
#               cutest_csgr_threaded \
#               cutest_cshcprod_threaded \
#               cutest_cshc_threaded \
#               cutest_cshj_threaded \
#               cutest_cshprod_threaded \
#               cutest_csh_threaded \
#               cutest_csjprod_threaded \
#               cutest_timings_threaded \
#               cutest_ubandh_threaded \
#               cutest_udh_threaded \
#               cutest_ueh_threaded \
#               cutest_ufn_threaded \
#               cutest_ugrdh_threaded \
#               cutest_ugreh_threaded \
#               cutest_ugrsh_threaded \
#               cutest_ugr_threaded \
#               cutest_uhprod_threaded \
#               cutest_uofg_threaded \
#               cutest_ureport_threaded \
#               cutest_usetup_threaded \
#               cutest_ushprod_threaded \
#               cutest_ush_threaded \
#               cutest )

#foreach pack ( cutest_chjprod cutest_chjprod_threaded )

#foreach pack ( cutest_cdhj cutest_cdhj_threaded )

#foreach pack ( cutest_chjprod cutest_chjprod_threaded )

#foreach pack ( cutest_cdimohp cutest_cdimsg \
#               cutest_chjprod cutest_chjprod_threaded \
#               cutest_cisgrp cutest_cohprods \
#               cutest_cohprodsp cutest_cohprods_threaded \
#               cutest_cshj cutest_cshj_threaded \
#               cutest_timings_threaded )

#foreach pack ( cutest_uterminate cutest_cterminate )
#foreach pack ( cutest_csjp cutest )
#foreach pack ( cutest_cshp cutest_csgrp cutest_csgrshp cutest_cchprodsp cutest )
#foreach pack ( cutest_cdimchp cutest_cchprods cutest_cchprods_threaded )
#foreach pack ( cutest_timings cutest_timings_threaded )

#foreach pack ( cutest_cdhc cutest_cdhc_threaded cutest )
#foreach pack ( cutest_ushprod cutest_cshprod cutest_cshcprod cutest_csjprod \
#               cutest_ushprod_threaded cutest_cshprod_threaded \
#               cutest_cshcprod_threaded cutest_csjprod_threaded \
#               cutest )

#foreach pack ( cutest_cdimen cutest_udimen )
#foreach pack ( cutest cutest_usetup_threaded cutest_csetup_threaded )
#foreach pack ( cutest cutest_ush cutest_ushp cutest_csh cutest_cshp )
#foreach pack ( cutest )
#foreach pack ( cutest_pname )
#foreach pack ( cutest_clfg cutest_clfg_threaded )
#foreach pack ( cutest_ccf )
#foreach pack ( cutest_ccfg )
#foreach pack ( cutest_ccfsg )
#foreach pack ( cutest_ccifg )
#foreach pack ( cutest_ccifsg )
#foreach pack ( cutest_cdh )
#foreach pack ( cutest_cstats )
#foreach pack ( cutest_cdimen )
#foreach pack ( cutest_cdimse )
#foreach pack ( cutest_cdimsh )
#foreach pack ( cutest_cdimsj )
#foreach pack ( cutest_ceh )
#foreach pack ( cutest_cfn )
#foreach pack ( cutest_cgr )
#foreach pack ( cutest_cgrdh )
#foreach pack ( cutest_chcprod )
#foreach pack ( cutest_chprod )
#foreach pack ( cutest_cidh )
#foreach pack ( cutest_cish )
#foreach pack ( cutest_cjprod )
#foreach pack ( cutest_cnames )
#foreach pack ( cutest_cofg )
#foreach pack ( cutest cutest_cofsg cutest_cofsg_threaded )
#foreach pack ( cutest_cofsg )
#foreach pack ( cutest_connames )
#foreach pack ( cutest_creport )
#foreach pack ( cutest_csetup )
#foreach pack ( cutest_csgr )
#foreach pack ( cutest_csgreh )
#foreach pack ( cutest_csgrsh )
#foreach pack ( cutest_csh )
#foreach pack ( cutest_cshc )
#foreach pack ( cutest_cvartype )
#foreach pack ( cutest_probname )
#foreach pack ( cutest_ubandh )
#foreach pack ( cutest_udh )
#foreach pack ( cutest_udimen )
#foreach pack ( cutest_udimse )
#foreach pack ( cutest_udimsh )
#foreach pack ( cutest_ueh )
#foreach pack ( cutest_ufn )
#foreach pack ( cutest_ugr )
#foreach pack ( cutest_ugrdh )
#foreach pack ( cutest_ugreh )
#foreach pack ( cutest_ugrsh )
#foreach pack ( cutest_uhprod )
#foreach pack ( cutest_unames )
#foreach pack ( cutest_uofg )
#foreach pack ( cutest_ureport )
#foreach pack ( cutest_usetup )
#foreach pack ( cutest_ush )
#foreach pack ( cutest_uvartype )
#foreach pack ( cutest_varnames )
#foreach pack ( cutest_ushprod )
#foreach pack ( cutest_cshprod )
#foreach pack ( cutest_cshcprod )
#foreach pack ( cutest_csjprod )
#foreach pack ( cutest_ccf_threaded )
#foreach pack ( cutest_ccfg_threaded )
#foreach pack ( cutest_ccfsg_threaded )
#foreach pack ( cutest_ccifg_threaded )
#foreach pack ( cutest_ccifsg_threaded )
#foreach pack ( cutest_cdh_threaded )
#foreach pack ( cutest_ceh_threaded )
#foreach pack ( cutest_cfn_threaded )
#foreach pack ( cutest_cgr_threaded )
#foreach pack ( cutest_cgrdh_threaded )
#foreach pack ( cutest_chcprod_threaded )
#foreach pack ( cutest_chprod_threaded )
#foreach pack ( cutest_cidh_threaded )
#foreach pack ( cutest_cish_threaded )
#foreach pack ( cutest_cjprod_threaded )
#foreach pack ( cutest_cofg_threaded )
#foreach pack ( cutest_cofsg_threaded )
#foreach pack ( cutest_creport_threaded )
#foreach pack ( cutest_csetup_threaded )
#foreach pack ( cutest_csgr_threaded )
#foreach pack ( cutest_csgreh_threaded )
#foreach pack ( cutest_csgrsh_threaded )
#foreach pack ( cutest_csh_threaded )
#foreach pack ( cutest_cshc_threaded )
#foreach pack ( cutest_ubandh_threaded )
#foreach pack ( cutest_udh_threaded )
#foreach pack ( cutest_ueh_threaded )
#foreach pack ( cutest_ufn_threaded )
#foreach pack ( cutest_ugr_threaded )
#foreach pack ( cutest_ugrdh_threaded )
#foreach pack ( cutest_ugreh_threaded )
#foreach pack ( cutest_ugrsh_threaded )
#foreach pack ( cutest_uhprod_threaded )
#foreach pack ( cutest_uofg_threaded )
#foreach pack ( cutest_ureport_threaded )
#foreach pack ( cutest_usetup_threaded )
#foreach pack ( cutest_ush_threaded )
#foreach pack ( cutest_ushprod_threaded )
#foreach pack ( cutest_cshprod_threaded )
#foreach pack ( cutest_cshcprod_threaded )
#foreach pack ( cutest_csjprod_threaded )

#foreach pack ( cutest_cifn cutest_cigr cutest_cisgr \
#               cutest_cifn_threaded cutest_cigr_threaded \
#               cutest_cisgr_threaded )

#foreach pack ( cutest_ureport cutest_ureport_threaded \
#               cutest_creport cutest_creport_threaded )

foreach pack ( cutest_classification )

  echo "    " $pack
  echo "      .. making pdf"
  groff -e -m man -T pdf $pack.3 > ../../doc/pdf/$pack.pdf
#  pdfroff -e -m man $pack.3 > ../../doc/pdf/$pack.pdf
  echo "      .. making html"
  groff -e -m man -T html -P "-Istem $pack-" -P "-i150" $pack.3 \
    > ${CUTEST}/doc/html/$pack.html
  mv *.png ${CUTEST}/doc/html
end
