        -1    IPRINT(1) specifies the frequency of output (<0: no output)
        -1    IPRINT(2) specifies content of output (0: minimal)
         3    METHOD    method used (1=Fletcher-Reeves,2=Polak-Ribiere,3=P-R+)
         0    IREST     no restart (0) or restart every n iterations (1)
     10000    MAXIT     specifies the maximum number of iterations
   0.00001    EPS       specifies the required gradient accuracy
