Begin MINOS Problem
   Minimize
   Rows                         5000
   Columns                     15000
   Elements                    75000

   Nonlinear Constraints        5000
   Nonlinear Variables         15000
   Jacobian                   SPARSE
   Derivative Level                3

   Hessian Dimension             500

   Iterations                  10000
   Major Iterations             1000
   Minor Iterations               40

   Print Level                     0
End MINOS Problem
