200                   maximum number of iterations
1e-12		      absolute tolerance
1e-8                  relative tolerance
1                     stopping test (1=our own, 2=delta_x, 3=gsl grad)
1                     write summary? (not 1 == don't write)
GSL.sum               summary file (max 20 characters)
1                     write iter summary? (not 1 == don't write)
GSL.iter_sum          summary file (max 20 characters)
