      tron      optimization method employed
      -1.0      stop if ||g(x)|| <= gatol
      -1.0      stop if ||g(x)|| / |f(x)| <= grtol
      -1.0      stop if ||g(x)|| / ||g(x_0)|| <= gttol
      -1.0      the initial trust-region radius
      -1.0      the regularization weight for least-squares problems
        -1      the maximum number of function evaluations
        -1      the maximum number of iterations
         0      print compomnents 1:sol and n-sol+1:n of the solution
