/*
 * assign names for each quadruple precision CUTEst routine using
 * the C pre-processor
 *
 * Nick Gould for CUTEst
 * initial version, 2023-11-11
 * this version 2024-08-27
 */

#define ELFUN_r ELFUN_q
#define ELFUN_flexible_r ELFUN_flexible_q
#define GROUP_r GROUP_q
#define RANGE_r RANGE_q
#define FORTRAN_open_r FORTRAN_open_q
#define FORTRAN_close_r FORTRAN_close_q
#define CUTEST_allocate_array_integer_r CUTEST_allocate_array_integer_q
#define CUTEST_allocate_array_real_r CUTEST_allocate_array_real_q
#define CUTEST_ccf_r CUTEST_ccf_q
#define CUTEST_ccf_threaded_r CUTEST_ccf_threaded_q
#define CUTEST_ccf_threadsafe_r CUTEST_ccf_threadsafe_q
#define CUTEST_ccfg_r CUTEST_ccfg_q
#define CUTEST_ccfg_threaded_r CUTEST_ccfg_threaded_q
#define CUTEST_ccfg_threadsafe_r CUTEST_ccfg_threadsafe_q
#define CUTEST_ccfsg_r CUTEST_ccfsg_q
#define CUTEST_ccfsg_threaded_r CUTEST_ccfsg_threaded_q
#define CUTEST_ccfsg_threadsafe_r CUTEST_ccfsg_threadsafe_q
#define CUTEST_cchprodsp_r CUTEST_cchprodsp_q
#define CUTEST_cchprodsp_threadsafe_r CUTEST_cchprodsp_threadsafe_q
#define CUTEST_cchprods_r CUTEST_cchprods_q
#define CUTEST_cchprods_threaded_r CUTEST_cchprods_threaded_q
#define CUTEST_cchprods_threadsafe_r CUTEST_cchprods_threadsafe_q
#define CUTEST_ccifg_r CUTEST_ccifg_q
#define CUTEST_ccifg_threaded_r CUTEST_ccifg_threaded_q
#define CUTEST_ccifg_threadsafe_r CUTEST_ccifg_threadsafe_q
#define CUTEST_ccifsg_r CUTEST_ccifsg_q
#define CUTEST_ccifsg_threaded_r CUTEST_ccifsg_threaded_q
#define CUTEST_ccifsg_threadsafe_r CUTEST_ccifsg_threadsafe_q
#define CUTEST_cconst_r CUTEST_cconst_q
#define CUTEST_cconst_threaded_r CUTEST_cconst_threaded_q
#define CUTEST_cconst_threadsafe_r CUTEST_cconst_threadsafe_q
#define CUTEST_cdhc_r CUTEST_cdhc_q
#define CUTEST_cdhc_threaded_r CUTEST_cdhc_threaded_q
#define CUTEST_cdhc_threadsafe_r CUTEST_cdhc_threadsafe_q
#define CUTEST_cdh_r CUTEST_cdh_q
#define CUTEST_cdh_threaded_r CUTEST_cdh_threaded_q
#define CUTEST_cdh_threadsafe_r CUTEST_cdh_threadsafe_q
#define CUTEST_cdhj_r CUTEST_cdhj_q
#define CUTEST_cdhj_threaded_r CUTEST_cdhj_threaded_q
#define CUTEST_cdhj_threadsafe_r CUTEST_cdhj_threadsafe_q
#define CUTEST_cdimchp_r CUTEST_cdimchp_q
#define CUTEST_cdimchp_threadsafe_r CUTEST_cdimchp_threadsafe_q
#define CUTEST_cdimen_r CUTEST_cdimen_q
#define CUTEST_cdimohp_r CUTEST_cdimohp_q
#define CUTEST_cdimohp_threadsafe_r CUTEST_cdimohp_threadsafe_q
#define CUTEST_cdimse_r CUTEST_cdimse_q
#define CUTEST_cdimse_threadsafe_r CUTEST_cdimse_threadsafe_q
#define CUTEST_cdimsg_r CUTEST_cdimsg_q
#define CUTEST_cdimsg_threadsafe_r CUTEST_cdimsg_threadsafe_q
#define CUTEST_cdimsh_r CUTEST_cdimsh_q
#define CUTEST_cdimsh_threadsafe_r CUTEST_cdimsh_threadsafe_q
#define CUTEST_cdimsj_r CUTEST_cdimsj_q
#define CUTEST_cdimsj_threadsafe_r CUTEST_cdimsj_threadsafe_q
#define CUTEST_ceh_r CUTEST_ceh_q
#define CUTEST_ceh_threaded_r CUTEST_ceh_threaded_q
#define CUTEST_ceh_threadsafe_r CUTEST_ceh_threadsafe_q
#define CUTEST_cfn_r CUTEST_cfn_q
#define CUTEST_cfn_threaded_r CUTEST_cfn_threaded_q
#define CUTEST_cfn_threadsafe_r CUTEST_cfn_threadsafe_q
#define CUTEST_cgrdh_r CUTEST_cgrdh_q
#define CUTEST_cgrdh_threaded_r CUTEST_cgrdh_threaded_q
#define CUTEST_cgrdh_threadsafe_r CUTEST_cgrdh_threadsafe_q
#define CUTEST_cgr_r CUTEST_cgr_q
#define CUTEST_cgr_threaded_r CUTEST_cgr_threaded_q
#define CUTEST_cgr_threadsafe_r CUTEST_cgr_threadsafe_q
#define CUTEST_chcprod_r CUTEST_chcprod_q
#define CUTEST_chcprod_threaded_r CUTEST_chcprod_threaded_q
#define CUTEST_chcprod_threadsafe_r CUTEST_chcprod_threadsafe_q
#define CUTEST_chjprod_r CUTEST_chjprod_q
#define CUTEST_chjprod_threaded_r CUTEST_chjprod_threaded_q
#define CUTEST_chjprod_threadsafe_r CUTEST_chjprod_threadsafe_q
#define CUTEST_chprod_r CUTEST_chprod_q
#define CUTEST_chprod_threaded_r CUTEST_chprod_threaded_q
#define CUTEST_chprod_threadsafe_r CUTEST_chprod_threadsafe_q
#define CUTEST_cidh_r CUTEST_cidh_q
#define CUTEST_cidh_threaded_r CUTEST_cidh_threaded_q
#define CUTEST_cidh_threadsafe_r CUTEST_cidh_threadsafe_q
#define CUTEST_cifn_r CUTEST_cifn_q
#define CUTEST_cifn_threaded_r CUTEST_cifn_threaded_q
#define CUTEST_cifn_threadsafe_r CUTEST_cifn_threadsafe_q
#define CUTEST_cigr_r CUTEST_cigr_q
#define CUTEST_cigr_threaded_r CUTEST_cigr_threaded_q
#define CUTEST_cigr_threadsafe_r CUTEST_cigr_threadsafe_q
#define CUTEST_Cint_ccfg_r CUTEST_Cint_ccfg_q
#define CUTEST_Cint_ccfsg_r CUTEST_Cint_ccfsg_q
#define CUTEST_Cint_cchprods_r CUTEST_Cint_cchprods_q
#define CUTEST_Cint_ccifg_r CUTEST_Cint_ccifg_q
#define CUTEST_Cint_ccifsg_r CUTEST_Cint_ccifsg_q
#define CUTEST_Cint_ceh_r CUTEST_Cint_ceh_q
#define CUTEST_Cint_cgrdh_r CUTEST_Cint_cgrdh_q
#define CUTEST_Cint_cgr_r CUTEST_Cint_cgr_q
#define CUTEST_Cint_chcprod_r CUTEST_Cint_chcprod_q
#define CUTEST_Cint_chjprod_r CUTEST_Cint_chjprod_q
#define CUTEST_Cint_chprod_r CUTEST_Cint_chprod_q
#define CUTEST_Cint_cjprod_r CUTEST_Cint_cjprod_q
#define CUTEST_Cint_clfg_r CUTEST_Cint_clfg_q
#define CUTEST_Cint_cofg_r CUTEST_Cint_cofg_q
#define CUTEST_Cint_cofsg_r CUTEST_Cint_cofsg_q
#define CUTEST_Cint_cohprods_r CUTEST_Cint_cohprods_q
#define CUTEST_Cint_cohprodsp_r CUTEST_cohprodsp_q
#define CUTEST_Cint_csetup_r CUTEST_Cint_csetup_q
#define CUTEST_Cint_csgreh_r CUTEST_Cint_csgreh_q
#define CUTEST_Cint_csgr_r CUTEST_Cint_csgr_q
#define CUTEST_Cint_csgrsh_r CUTEST_Cint_csgrsh_q
#define CUTEST_Cint_cshcprod_r CUTEST_Cint_cshcprod_q
#define CUTEST_Cint_cshprod_r CUTEST_Cint_cshprod_q
#define CUTEST_Cint_csjprod_r CUTEST_Cint_csjprod_q
#define CUTEST_Cint_ueh_r CUTEST_Cint_ueh_q
#define CUTEST_cint_ugreh_r CUTEST_cint_ugreh_q
#define CUTEST_Cint_uhprod_r CUTEST_Cint_uhprod_q
#define CUTEST_Cint_uofg_r CUTEST_Cint_uofg_q
#define CUTEST_Cint_ushprod_r CUTEST_Cint_ushprod_q
#define CUTEST_Cint_classification_r CUTEST_Cint_classification_q
#define CUTEST_Cint_pname_r CUTEST_Cint_pname_q
#define CUTEST_Cint_unames_r CUTEST_Cint_unames_q
#define CUTEST_Cint_cnames_r CUTEST_Cint_cnames_q
#define CUTEST_Cint_probname_r CUTEST_Cint_probname_q
#define CUTEST_Cint_varnames_r CUTEST_Cint_varnames_q
#define CUTEST_Cint_connames_r CUTEST_Cint_connames_q
#define CUTEST_Cint_cnoobj_r CUTEST_Cint_cnoobj_q
#define CUTEST_cisgrp_r CUTEST_cisgrp_q
#define CUTEST_cisgrp_threaded_r CUTEST_cisgrp_threaded_q
#define CUTEST_cisgrp_threadsafe_r CUTEST_cisgrp_threadsafe_q
#define CUTEST_cisgr_r CUTEST_cisgr_q
#define CUTEST_cisgr_threaded_r CUTEST_cisgr_threaded_q
#define CUTEST_cisgr_threadsafe_r CUTEST_cisgr_threadsafe_q
#define CUTEST_cish_r CUTEST_cish_q
#define CUTEST_cish_threaded_r CUTEST_cish_threaded_q
#define CUTEST_cish_threadsafe_r CUTEST_cish_threadsafe_q
#define CUTEST_cjprod_r CUTEST_cjprod_q
#define CUTEST_cjprod_threaded_r CUTEST_cjprod_threaded_q
#define CUTEST_cjprod_threadsafe_r CUTEST_cjprod_threadsafe_q
#define CUTEST_clfg_r CUTEST_clfg_q
#define CUTEST_clfg_threaded_r CUTEST_clfg_threaded_q
#define CUTEST_clfg_threadsafe_r CUTEST_clfg_threadsafe_q
#define CUTEST_cnames_r CUTEST_cnames_q
#define CUTEST_cnames_threadsafe_r CUTEST_cnames_threadsafe_q
#define CUTEST_cnoobj_r CUTEST_cnoobj_q
#define CUTEST_cofg_r CUTEST_cofg_q
#define CUTEST_cofg_threaded_r CUTEST_cofg_threaded_q
#define CUTEST_cofg_threadsafe_r CUTEST_cofg_threadsafe_q
#define CUTEST_cofsg_r CUTEST_cofsg_q
#define CUTEST_cofsg_threaded_r CUTEST_cofsg_threaded_q
#define CUTEST_cofsg_threadsafe_r CUTEST_cofsg_threadsafe_q
#define CUTEST_cohprodsp_r CUTEST_cohprodsp_q
#define CUTEST_cohprodsp_threadsafe_r CUTEST_cohprodsp_threadsafe_q
#define CUTEST_cohprods_r CUTEST_cohprods_q
#define CUTEST_cohprods_threaded_r CUTEST_cohprods_threaded_q
#define CUTEST_cohprods_threadsafe_r CUTEST_cohprods_threadsafe_q
#define CUTEST_connames_r CUTEST_connames_q
#define CUTEST_connames_threadsafe_r CUTEST_connames_threadsafe_q
#define CUTEST_creport_r CUTEST_creport_q
#define CUTEST_creport_threaded_r CUTEST_creport_threaded_q
#define CUTEST_creport_threadsafe_r CUTEST_creport_threadsafe_q
#define CUTEST_csetup_r CUTEST_csetup_q
#define CUTEST_csetup_threaded_r CUTEST_csetup_threaded_q
#define CUTEST_csetup_threadsafe_r CUTEST_csetup_threadsafe_q
#define CUTEST_csgreh_r CUTEST_csgreh_q
#define CUTEST_csgreh_threaded_r CUTEST_csgreh_threaded_q
#define CUTEST_csgreh_threadsafe_r CUTEST_csgreh_threadsafe_q
#define CUTEST_csgrp_r CUTEST_csgrp_q
#define CUTEST_csgrp_threaded_r CUTEST_csgrp_threaded_q
#define CUTEST_csgrp_threadsafe_r CUTEST_csgrp_threadsafe_q
#define CUTEST_csgr_r CUTEST_csgr_q
#define CUTEST_csgrshp_r CUTEST_csgrshp_q
#define CUTEST_csgrshp_threadsafe_r CUTEST_csgrshp_threadsafe_q
#define CUTEST_csgrsh_r CUTEST_csgrsh_q
#define CUTEST_csgrsh_threaded_r CUTEST_csgrsh_threaded_q
#define CUTEST_csgrsh_threadsafe_r CUTEST_csgrsh_threadsafe_q
#define CUTEST_csgr_threaded_r CUTEST_csgr_threaded_q
#define CUTEST_csgr_threadsafe_r CUTEST_csgr_threadsafe_q
#define CUTEST_cshcprod_r CUTEST_cshcprod_q
#define CUTEST_cshcprod_threaded_r CUTEST_cshcprod_threaded_q
#define CUTEST_cshcprod_threadsafe_r CUTEST_cshcprod_threadsafe_q
#define CUTEST_cshc_r CUTEST_cshc_q
#define CUTEST_cshc_threaded_r CUTEST_cshc_threaded_q
#define CUTEST_cshc_threadsafe_r CUTEST_cshc_threadsafe_q
#define CUTEST_cshj_r CUTEST_cshj_q
#define CUTEST_cshj_threaded_r CUTEST_cshj_threaded_q
#define CUTEST_cshj_threadsafe_r CUTEST_cshj_threadsafe_q
#define CUTEST_cshp_r CUTEST_cshp_q
#define CUTEST_cshprod_r CUTEST_cshprod_q
#define CUTEST_cshprod_threaded_r CUTEST_cshprod_threaded_q
#define CUTEST_cshprod_threadsafe_r CUTEST_cshprod_threadsafe_q
#define CUTEST_cshp_threadsafe_r CUTEST_cshp_threadsafe_q
#define CUTEST_csh_r CUTEST_csh_q
#define CUTEST_csh_threaded_r CUTEST_csh_threaded_q
#define CUTEST_csh_threadsafe_r CUTEST_csh_threadsafe_q
#define CUTEST_csjp_r CUTEST_csjp_q
#define CUTEST_csjprod_r CUTEST_csjprod_q
#define CUTEST_csjprod_threaded_r CUTEST_csjprod_threaded_q
#define CUTEST_csjprod_threadsafe_r CUTEST_csjprod_threadsafe_q
#define CUTEST_csjp_threadsafe_r CUTEST_csjp_threadsafe_q
#define CUTEST_cstats_r CUTEST_cstats_q
#define CUTEST_cstats_threadsafe_r CUTEST_cstats_threadsafe_q
#define CUTEST_cterminate_r CUTEST_cterminate_q
#define CUTEST_cvartype_r CUTEST_cvartype_q
#define CUTEST_cvartype_threadsafe_r CUTEST_cvartype_threadsafe_q
#define CUTEST_extend_array_integer_r CUTEST_extend_array_integer_q
#define CUTEST_extend_array_real_r CUTEST_extend_array_real_q
#define CUTEST_initialize_thread_r CUTEST_initialize_thread_q
#define CUTEST_LQP_create_r CUTEST_LQP_create_q
#define CUTEST_newthread_threadsafe_r CUTEST_newthread_threadsafe_q
#define CUTEST_classification_r CUTEST_classification_q
#define CUTEST_pname_r CUTEST_pname_q
#define CUTEST_problem_qetup_r CUTEST_problem_qetup_q
#define CUTEST_problem_terminate_r CUTEST_problem_terminate_q
#define CUTEST_probname_r CUTEST_probname_q
#define CUTEST_probname_threadsafe_r CUTEST_probname_threadsafe_q
#define CUTEST_reorder_by_rows_r CUTEST_reorder_by_rows_q
#define CUTEST_qparse_hessian_by_rows_r CUTEST_qparse_hessian_by_rows_q
#define CUTEST_qymmh_r CUTEST_qymmh_q
#define CUTEST_terminate_data_r CUTEST_terminate_data_q
#define CUTEST_terminate_work_r CUTEST_terminate_work_q
#define CUTEST_timings_r CUTEST_timings_q
#define CUTEST_timings_threaded_r CUTEST_timings_threaded_q
#define CUTEST_timings_threadsafe_r CUTEST_timings_threadsafe_q
#define CUTEST_ubandh_r CUTEST_ubandh_q
#define CUTEST_ubandh_threaded_r CUTEST_ubandh_threaded_q
#define CUTEST_ubandh_threadsafe_r CUTEST_ubandh_threadsafe_q
#define CUTEST_udh_r CUTEST_udh_q
#define CUTEST_udh_threaded_r CUTEST_udh_threaded_q
#define CUTEST_udh_threadsafe_r CUTEST_udh_threadsafe_q
#define CUTEST_udimen_r CUTEST_udimen_q
#define CUTEST_udimse_r CUTEST_udimse_q
#define CUTEST_udimse_threadsafe_r CUTEST_udimse_threadsafe_q
#define CUTEST_udimsh_r CUTEST_udimsh_q
#define CUTEST_udimsh_threadsafe_r CUTEST_udimsh_threadsafe_q
#define CUTEST_ueh_r CUTEST_ueh_q
#define CUTEST_ueh_threaded_r CUTEST_ueh_threaded_q
#define CUTEST_ueh_threadsafe_r CUTEST_ueh_threadsafe_q
#define CUTEST_ufn_r CUTEST_ufn_q
#define CUTEST_ufn_threaded_r CUTEST_ufn_threaded_q
#define CUTEST_ufn_threadsafe_r CUTEST_ufn_threadsafe_q
#define CUTEST_ugrdh_r CUTEST_ugrdh_q
#define CUTEST_ugrdh_threaded_r CUTEST_ugrdh_threaded_q
#define CUTEST_ugrdh_threadsafe_r CUTEST_ugrdh_threadsafe_q
#define CUTEST_ugreh_r CUTEST_ugreh_q
#define CUTEST_ugreh_threaded_r CUTEST_ugreh_threaded_q
#define CUTEST_ugreh_threadsafe_r CUTEST_ugreh_threadsafe_q
#define CUTEST_ugr_r CUTEST_ugr_q
#define CUTEST_ugrsh_r CUTEST_ugrsh_q
#define CUTEST_ugrsh_threaded_r CUTEST_ugrsh_threaded_q
#define CUTEST_ugrsh_threadsafe_r CUTEST_ugrsh_threadsafe_q
#define CUTEST_ugr_threaded_r CUTEST_ugr_threaded_q
#define CUTEST_ugr_threadsafe_r CUTEST_ugr_threadsafe_q
#define CUTEST_uhprod_r CUTEST_uhprod_q
#define CUTEST_uhprod_threaded_r CUTEST_uhprod_threaded_q
#define CUTEST_uhprod_threadsafe_r CUTEST_uhprod_threadsafe_q
#define CUTEST_unames_r CUTEST_unames_q
#define CUTEST_unames_threadsafe_r CUTEST_unames_threadsafe_q
#define CUTEST_uofg_r CUTEST_uofg_q
#define CUTEST_uofg_threaded_r CUTEST_uofg_threaded_q
#define CUTEST_uofg_threadsafe_r CUTEST_uofg_threadsafe_q
#define CUTEST_ureport_r CUTEST_ureport_q
#define CUTEST_ureport_threaded_r CUTEST_ureport_threaded_q
#define CUTEST_ureport_threadsafe_r CUTEST_ureport_threadsafe_q
#define CUTEST_usetup_r CUTEST_usetup_q
#define CUTEST_usetup_threaded_r CUTEST_usetup_threaded_q
#define CUTEST_usetup_threadsafe_r CUTEST_usetup_threadsafe_q
#define CUTEST_ushp_r CUTEST_ushp_q
#define CUTEST_ushprod_r CUTEST_ushprod_q
#define CUTEST_ushprod_threaded_r CUTEST_ushprod_threaded_q
#define CUTEST_ushprod_threadsafe_r CUTEST_ushprod_threadsafe_q
#define CUTEST_ushp_threadsafe_r CUTEST_ushp_threadsafe_q
#define CUTEST_ush_r CUTEST_ush_q
#define CUTEST_ush_threaded_r CUTEST_ush_threaded_q
#define CUTEST_ush_threadsafe_r CUTEST_ush_threadsafe_q
#define CUTEST_uterminate_r CUTEST_uterminate_q
#define CUTEST_uvartype_r CUTEST_uvartype_q
#define CUTEST_uvartype_threadsafe_r CUTEST_uvartype_threadsafe_q
#define CUTEST_varnames_r CUTEST_varnames_q
#define CUTEST_varnames_threadsafe_r CUTEST_varnames_threadsafe_q

#define CUTEST_ufn_c_r            CUTEST_ufn_c_q            
#define CUTEST_ugr_c_r            CUTEST_ugr_c_q            
#define CUTEST_ubandh_c_r         CUTEST_ubandh_c_q         
#define CUTEST_udh_c_r            CUTEST_udh_c_q            
#define CUTEST_ushp_c_r           CUTEST_ushp_c_q           
#define CUTEST_ush_c_r            CUTEST_ush_c_q            
#define CUTEST_ueh_c_r            CUTEST_ueh_c_q            
#define CUTEST_ugrdh_c_r          CUTEST_ugrdh_c_q          
#define CUTEST_ugrsh_c_r          CUTEST_ugrsh_c_q          
#define CUTEST_ugreh_c_r          CUTEST_ugreh_c_q          
#define CUTEST_ushprod_c_r        CUTEST_ushprod_c_q        
#define CUTEST_cfn_c_r            CUTEST_cfn_c_q            
#define CUTEST_cconst_c_r         CUTEST_cconst_c_q         
#define CUTEST_cofsg_c_r          CUTEST_cofsg_c_q          
#define CUTEST_ccfg_c_r           CUTEST_ccfg_c_q           
#define CUTEST_ccf_c_r            CUTEST_ccf_c_q            
#define CUTEST_cgr_c_r            CUTEST_cgr_c_q            
#define CUTEST_csgr_c_r           CUTEST_csgr_c_q           
#define CUTEST_csgrp_c_r          CUTEST_csgrp_c_q          
#define CUTEST_csjp_c_r           CUTEST_csjp_c_q           
#define CUTEST_ccfsg_c_r          CUTEST_ccfsg_c_q          
#define CUTEST_ccifg_c_r          CUTEST_ccifg_c_q          
#define CUTEST_ccifsg_c_r         CUTEST_ccifsg_c_q         
#define CUTEST_cgrdh_c_r          CUTEST_cgrdh_c_q          
#define CUTEST_cdh_c_r            CUTEST_cdh_c_q            
#define CUTEST_cdhc_c_r           CUTEST_cdhc_c_q           
#define CUTEST_cdhj_c_r           CUTEST_cdhj_c_q           
#define CUTEST_cshp_c_r           CUTEST_cshp_c_q           
#define CUTEST_csh_c_r            CUTEST_csh_c_q            
#define CUTEST_cshc_c_r           CUTEST_cshc_c_q           
#define CUTEST_cshj_c_r           CUTEST_cshj_c_q           
#define CUTEST_ceh_c_r            CUTEST_ceh_c_q            
#define CUTEST_cifn_c_r           CUTEST_cifn_c_q           
#define CUTEST_cigr_c_r           CUTEST_cigr_c_q           
#define CUTEST_cisgr_c_r          CUTEST_cisgr_c_q          
#define CUTEST_cisgrp_c_r         CUTEST_cisgrp_c_q         
#define CUTEST_cidh_c_r           CUTEST_cidh_c_q           
#define CUTEST_cish_c_r           CUTEST_cish_c_q           
#define CUTEST_csgrsh_c_r         CUTEST_csgrsh_c_q         
#define CUTEST_csgrshp_c_r        CUTEST_csgrshp_c_q        
#define CUTEST_csgreh_c_r         CUTEST_csgreh_c_q         
#define CUTEST_cshprod_c_r        CUTEST_cshprod_c_q        
#define CUTEST_cshcprod_c_r       CUTEST_cshcprod_c_q       
#define CUTEST_csjprod_c_r        CUTEST_csjprod_c_q        
#define CUTEST_cchprods_c_r       CUTEST_cchprods_c_q       
#define CUTEST_cchprodsp_c_r      CUTEST_cchprodsp_c_q      
#define CUTEST_cohprods_c_r       CUTEST_cohprods_c_q       
#define CUTEST_cohprodsp_c_r      CUTEST_cohprodsp_c_q      

#define CUTEST_uofg_c_r           CUTEST_uofg_c_q           
#define CUTEST_uhprod_c_r         CUTEST_uhprod_c_q         
#define CUTEST_cofg_c_r           CUTEST_cofg_c_q           
#define CUTEST_clfg_c_r           CUTEST_clfg_c_q           
#define CUTEST_chprod_c_r         CUTEST_chprod_c_q         
#define CUTEST_chcprod_c_r        CUTEST_chcprod_c_q        
#define CUTEST_chjprod_c_r        CUTEST_chjprod_c_q        
#define CUTEST_cjprod_c_r         CUTEST_cjprod_c_q

#define CUTEST_usetup_c_r         CUTEST_usetup_c_q         
#define CUTEST_csetup_c_r         CUTEST_csetup_c_q         

#define CUTEST_udimen_c_r         CUTEST_udimen_c_q         
#define CUTEST_udimsh_c_r         CUTEST_udimsh_c_q         
#define CUTEST_udimse_c_r         CUTEST_udimse_c_q         
#define CUTEST_uvartype_c_r       CUTEST_uvartype_c_q       
#define CUTEST_unames_c_r         CUTEST_unames_c_q         
#define CUTEST_ureport_c_r        CUTEST_ureport_c_q        

#define CUTEST_cdimen_c_r         CUTEST_cdimen_c_q         
#define CUTEST_cnoobj_c_r         CUTEST_cnoobj_c_q         
#define CUTEST_cdimsg_c_r         CUTEST_cdimsg_c_q         
#define CUTEST_cdimsj_c_r         CUTEST_cdimsj_c_q         
#define CUTEST_cdimsh_c_r         CUTEST_cdimsh_c_q         
#define CUTEST_cdimohp_c_r        CUTEST_cdimohp_c_q        
#define CUTEST_cdimchp_c_r        CUTEST_cdimchp_c_q        
#define CUTEST_cdimse_c_r         CUTEST_cdimse_c_q         
#define CUTEST_cstats_c_r         CUTEST_cstats_c_q         
#define CUTEST_cvartype_c_r       CUTEST_cvartype_c_q       
#define CUTEST_cnames_c_r         CUTEST_cnames_c_q         
#define CUTEST_creport_c_r        CUTEST_creport_c_q        

#define CUTEST_classification_c_r CUTEST_classification_c_q 
#define CUTEST_connames_c_r       CUTEST_connames_c_q       
#define CUTEST_pname_c_r          CUTEST_pname_c_q          
#define CUTEST_probname_c_r       CUTEST_probname_c_q       
#define CUTEST_varnames_c_r       CUTEST_varnames_c_q       

#define CUTEST_uterminate_c_r     CUTEST_uterminate_c_q     
#define CUTEST_cterminate_c_r     CUTEST_cterminate_c_q     

#define FORTRAN_open_c_r          FORTRAN_open_c_q          
#define FORTRAN_close_c_r         FORTRAN_close_c_q                  
