         5     P        the number of vectors to hold factorization fill-in
      1000     MAXIT    the maximum number of iterations,
    0.0D+0     FATOL    the absolute error desired in the function
   1.0D-12     FRTOL    the relative error desired in the function
  -1.0D+20     FMIN     a lower bound for the function
    1.0D-1     CGTOL    the relative CG decrease required per iteration
    1.0D-5     GTOL     the required norm of the projected gradient
